
name: Sync with Upstream
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'DDIDDI'
          git config --global user.email 'bananaqick@gmail.com'

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/fridge-rescue/fridge-rescue-client.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit

